[package]
name = "testando_rust_ml"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
polars = { version = "0.40.0", features = ["lazy", "temporal", "describe", "json", "parquet", "dtype-datetime"] }
